"use client";

import React from "react";
import { CheckCircle2, Clock, PlayCircle, AlertCircle } from "lucide-react";

interface TaskItem {
  id?: string;
  title: string;
  description?: str;
  priority?: string;
  status?: string;
  category?: str;
  deadline?: str;
  progress?: number;
}

interface ExecutionBoardProps {
  tasks?: TaskItem[];
  nextSteps?: string[];
  onTaskStatusChange?: (taskId: string, newStatus: string) => void;
}

export function ExecutionBoard({ tasks = [], nextSteps = [], onTaskStatusChange }: ExecutionBoardProps) {
  const getPriorityColor = (p = "MEDIUM") => {
    switch (p.toUpperCase()) {
      case "CRITICAL":
      case "HIGH":
        return "#ef4444";
      case "MEDIUM":
        return "#f59e0b";
      default:
        return "#10b981";
    }
  };

  return (
    <div className="glass-panel" style={{ borderRadius: 20, padding: 24 }}>
      <div style={{ marginBottom: 20 }}>
        <h3 style={{ fontSize: 18, fontWeight: 800, color: "#fff", margin: 0 }}>
          Execution & Validation Plan
        </h3>
        <p style={{ color: "#94a3b8", fontSize: 13, margin: "2px 0 0" }}>
          Generated by Execution Planner Agent with task status tracking
        </p>
      </div>

      {/* Immediate Next Steps list if available */}
      {nextSteps.length > 0 && (
        <div style={{ background: "rgba(56,189,248,0.08)", border: "1px solid rgba(56,189,248,0.2)", borderRadius: 12, padding: 16, marginBottom: 20 }}>
          <span style={{ fontSize: 11, fontWeight: 700, color: "#38bdf8", textTransform: "uppercase", letterSpacing: "0.05em" }}>
            Immediate Next Steps
          </span>
          <div style={{ display: "grid", gap: 8, marginTop: 8 }}>
            {nextSteps.map((step, idx) => (
              <div key={idx} style={{ display: "flex", alignItems: "flex-start", gap: 8, fontSize: 13, color: "#f1f5f9" }}>
                <span style={{ color: "#38bdf8", fontWeight: 700 }}>{idx + 1}.</span>
                <span>{step}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Task list */}
      <div style={{ display: "grid", gap: 12 }}>
        {tasks.map((task, idx) => {
          const status = (task.status || "pending").toLowerCase();
          const priority = task.priority || "MEDIUM";

          return (
            <div
              key={task.id || idx}
              style={{
                background: "rgba(15,23,42,0.5)",
                border: "1px solid rgba(255,255,255,0.08)",
                borderRadius: 12,
                padding: 14,
                display: "flex",
                alignItems: "center",
                justifySpace: "space-between",
                gap: 12,
              }}
            >
              <div style={{ flex: 1 }}>
                <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 4 }}>
                  <span style={{ color: "#fff", fontWeight: 700, fontSize: 14 }}>{task.title}</span>
                  <span
                    style={{
                      fontSize: 10,
                      fontWeight: 700,
                      color: getPriorityColor(priority),
                      border: `1px solid ${getPriorityColor(priority)}`,
                      padding: "1px 6px",
                      borderRadius: 4,
                    }}
                  >
                    {priority}
                  </span>
                  {task.category && (
                    <span style={{ fontSize: 11, color: "#64748b", textTransform: "lowercase" }}>
                      #{task.category}
                    </span>
                  )}
                </div>
                {task.description && (
                  <p style={{ color: "#94a3b8", fontSize: 12, margin: 0 }}>{task.description}</p>
                )}
              </div>

              <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                {status === "completed" ? (
                  <span style={{ display: "inline-flex", alignItems: "center", gap: 4, color: "#34d399", fontSize: 12, fontWeight: 700 }}>
                    <CheckCircle2 style={{ width: 16, height: 16 }} /> Done
                  </span>
                ) : status === "in_progress" ? (
                  <span style={{ display: "inline-flex", alignItems: "center", gap: 4, color: "#38bdf8", fontSize: 12, fontWeight: 700 }}>
                    <PlayCircle style={{ width: 16, height: 16 }} /> In Progress
                  </span>
                ) : (
                  <span style={{ display: "inline-flex", alignItems: "center", gap: 4, color: "#94a3b8", fontSize: 12 }}>
                    <Clock style={{ width: 16, height: 16 }} /> Pending
                  </span>
                )}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
